package com.github.appreciated.demo.helper.view.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class HorizontalHeaderDesign extends HorizontalLayout {
    protected Image image;
    protected Label header;
    protected HorizontalLayout descriptionWrapper;
    protected Label subtitle;
    protected HorizontalLayout componentWrapper;
    protected CssLayout componentHolder;

    public HorizontalHeaderDesign() {
        Design.read(this);
    }
}
